apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cadqstream-prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      timeInterval: 15s

  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    url: redis://cadqstream-redis:6379
    isDefault: false
    version: 1
    editable: true
    jsonData:
      password: "${REDIS_PASSWORD}"
      tlsAuth: false
      tlsSkipVerify: false

  - name: MinIO
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cadqstream-minio:9000/minio/v2/metrics/cluster
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
