KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
    user_kafka-user="change-kafka-password";
};

Client {
  org.apache.kafka.common.security.plain.PlainLoginModule required
    user_kafka-user="change-kafka-password";
};
