"""
SLO Burn-Rate Calculation and Tracking for CA-DQStream + MemStream.

Implements multi-window burn-rate alerting:
- 1h window: Fast burn-rate (14.4x multiplier)
- 6h window: Medium burn-rate (6x multiplier)
- 3d window: Slow burn-rate (3x multiplier)

Multipliers based on error budget alerting best practices:
https://sre.google/workbook/alerting-on-slos/

Usage:
    from monitoring.slo import SLOBurnRateTracker, SLOConfig
    
    tracker = SLOBurnRateTracker(
        slo_config=SLOConfig(
            latency_p99_target_ms=100.0,
            error_rate_target=0.001,
            availability_target=0.999,
        ),
        neighborhoods=["manhattan", "brooklyn", "queens"],
    )
    
    # In main loop:
    tracker.update(
        neighborhood="manhattan",
        latency_p99_ms=150.0,
        error_count=5,
        total_requests=10000,
    )
    
    alerts = tracker.check_alerts()
    for alert in alerts:
        publish_alert(alert)
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
from enum import Enum
import time
import threading
import math


class SLOType(Enum):
    """Types of SLOs being tracked."""
    LATENCY = "latency"
    ERROR_RATE = "error_rate"
    AVAILABILITY = "availability"


class BurnRateWindow(Enum):
    """Burn-rate calculation windows."""
    FAST_1H = "1h"
    MEDIUM_6H = "6h"
    SLOW_3D = "3d"


@dataclass
class SLOConfig:
    """Configuration for an SLO target."""
    
    latency_p99_target_ms: float = 100.0
    error_rate_target: float = 0.001  # 0.1%
    availability_target: float = 0.999  # 99.9%
    
    # Window sizes in seconds
    window_1h_seconds: float = 3600
    window_6h_seconds: float = 21600
    window_3d_seconds: float = 259200  # 3 days
    
    # Burn-rate thresholds (multiplier × target = alerting threshold)
    fast_burn_multiplier: float = 14.4   # 1h window: 5% budget burned/hour
    medium_burn_multiplier: float = 6.0  # 6h window: 10% budget burned/hour
    slow_burn_multiplier: float = 3.0    # 3d window: 100% budget burned in window


@dataclass
class WindowedMetrics:
    """Metrics aggregated over a time window."""
    
    window_seconds: float
    samples: int = 0
    error_count: int = 0
    latency_sum_ms: float = 0.0
    latency_max_ms: float = 0.0
    latency_p99_ms: float = 0.0  # Approximated via percentiles
    
    # For rolling percentiles
    latency_samples: List[float] = field(default_factory=list)
    
    def add_sample(self, latency_ms: float, is_error: bool = False):
        """Add a sample to the window."""
        self.samples += 1
        self.latency_sum_ms += latency_ms
        self.latency_max_ms = max(self.latency_max_ms, latency_ms)
        self.latency_samples.append(latency_ms)
        
        if is_error:
            self.error_count += 1
        
        # Keep samples within window (simplified - real impl needs timestamps)
        if len(self.latency_samples) > 10000:
            self.latency_samples = self.latency_samples[-5000:]
    
    def compute_p99(self) -> float:
        """Compute approximate p99 latency."""
        if not self.latency_samples:
            return 0.0
        sorted_samples = sorted(self.latency_samples)
        idx = int(len(sorted_samples) * 0.99)
        return sorted_samples[min(idx, len(sorted_samples) - 1)]
    
    def reset(self):
        """Reset all metrics."""
        self.samples = 0
        self.error_count = 0
        self.latency_sum_ms = 0.0
        self.latency_max_ms = 0.0
        self.latency_samples.clear()


@dataclass
class SLOAlert:
    """Alert generated by SLO burn-rate breach."""
    
    alert_id: str
    neighborhood: str
    slo_type: SLOType
    burn_rate: float
    threshold: float
    budget_remaining_seconds: float
    budget_total_seconds: float
    window: BurnRateWindow
    severity: str  # warning | critical
    message: str
    timestamp: float = field(default_factory=time.time)
    
    def to_dict(self) -> Dict:
        return {
            "alert_id": self.alert_id,
            "neighborhood": self.neighborhood,
            "slo_type": self.slo_type.value,
            "burn_rate": round(self.burn_rate, 2),
            "threshold": self.threshold,
            "budget_remaining_seconds": round(self.budget_remaining_seconds, 1),
            "budget_total_seconds": round(self.budget_total_seconds, 1),
            "window": self.window.value,
            "severity": self.severity,
            "message": self.message,
            "timestamp": self.timestamp,
        }


class SLOBurnRateTracker:
    """
    Multi-window SLO burn-rate tracker.
    
    Tracks burn rates across multiple time windows and generates
    alerts when burn rates exceed thresholds.
    
    Burn-rate = (observed_bad / total) / (target_bad / total_window)
    
    Example:
        - Target: 99.9% availability (0.1% errors)
        - 1h window: 3600 seconds
        - Budget: 3600 * 0.001 = 3.6 seconds of errors per hour
        
        If we observe 10 errors in 5 minutes (300s):
        - Burn rate = (10 errors / 300s) / (3.6 errors / 3600s)
        - Burn rate = 0.033 / 0.001 = 33x
        
        At 33x burn rate, we'd exhaust the 1h budget in ~2 minutes!
    """
    
    def __init__(
        self,
        slo_config: SLOConfig,
        neighborhoods: List[str],
    ):
        self.slo_config = slo_config
        self.neighborhoods = neighborhoods
        
        # Per-neighborhood, per-window metrics
        self._metrics: Dict[str, Dict[BurnRateWindow, WindowedMetrics]] = {}
        self._error_budget_consumed: Dict[str, float] = {}  # seconds consumed
        self._last_update: Dict[str, float] = {}
        
        # Alert tracking
        self._active_alerts: Dict[str, SLOAlert] = {}
        self._alert_history: List[SLOAlert] = []
        self._lock = threading.Lock()
        
        # Initialize metrics for each neighborhood
        for neighborhood in neighborhoods:
            self._init_neighborhood(neighborhood)
    
    def _init_neighborhood(self, neighborhood: str):
        """Initialize metrics tracking for a neighborhood."""
        self._metrics[neighborhood] = {
            BurnRateWindow.FAST_1H: WindowedMetrics(
                window_seconds=self.slo_config.window_1h_seconds
            ),
            BurnRateWindow.MEDIUM_6H: WindowedMetrics(
                window_seconds=self.slo_config.window_6h_seconds
            ),
            BurnRateWindow.SLOW_3D: WindowedMetrics(
                window_seconds=self.slo_config.window_3d_seconds
            ),
        }
        self._error_budget_consumed[neighborhood] = 0.0
        self._last_update[neighborhood] = time.time()
    
    def update(
        self,
        neighborhood: str,
        latency_p99_ms: Optional[float] = None,
        error_count: int = 0,
        total_requests: int = 0,
    ):
        """
        Update metrics for a neighborhood.
        
        Args:
            neighborhood: Neighborhood identifier
            latency_p99_ms: Measured p99 latency
            error_count: Number of errors in this sample period
            total_requests: Total requests in this sample period
        """
        with self._lock:
            if neighborhood not in self._metrics:
                self._init_neighborhood(neighborhood)
            
            now = time.time()
            elapsed = now - self._last_update[neighborhood]
            
            # Update each window
            for window, metrics in self._metrics[neighborhood].items():
                # Add samples to all windows
                if latency_p99_ms is not None:
                    metrics.add_sample(latency_p99_ms, is_error=False)
                
                # Update error rate (spread errors across windows)
                if error_count > 0 and total_requests > 0:
                    error_rate = error_count / total_requests
                    for _ in range(min(error_count, 100)):  # Limit iterations
                        metrics.add_sample(0, is_error=True)
            
            # Update error budget consumption
            if total_requests > 0:
                observed_error_rate = error_count / total_requests
                budget_consumed = elapsed * observed_error_rate
                self._error_budget_consumed[neighborhood] += budget_consumed
            
            self._last_update[neighborhood] = now
    
    def compute_burn_rates(self, neighborhood: str) -> Dict:
        """
        Compute burn rates across all windows and SLO types.
        
        Returns:
            Dict mapping (window, slo_type) to burn_rate
        """
        rates = {}
        
        for window, metrics in self._metrics.get(neighborhood, {}).items():
            if metrics.samples == 0:
                continue
            
            window_seconds = metrics.window_seconds
            
            # Error rate burn rate
            if metrics.samples > 0:
                observed_error_rate = metrics.error_count / metrics.samples
                target_error_rate = self.slo_config.error_rate_target
                
                # Normalize to same time scale
                error_burn_rate = observed_error_rate / target_error_rate
                
                rates[(window, SLOType.ERROR_RATE)] = error_burn_rate
            
            # Latency burn rate (if p99 available)
            if metrics.latency_samples:
                p99 = metrics.compute_p99()
                target_latency = self.slo_config.latency_p99_target_ms
                
                if target_latency > 0:
                    latency_burn_rate = p99 / target_latency
                    rates[(window, SLOType.LATENCY)] = latency_burn_rate
        
        return rates
    
    def check_alerts(self) -> List[SLOAlert]:
        """
        Check for SLO burn-rate alerts.
        
        Returns:
            List of new/ongoing alerts
        """
        alerts = []
        now = time.time()
        
        for neighborhood in self.neighborhoods:
            burn_rates = self.compute_burn_rates(neighborhood)
            
            for (window, slo_type), burn_rate in burn_rates.items():
                # Determine threshold based on window
                if window == BurnRateWindow.FAST_1H:
                    threshold = self.slo_config.fast_burn_multiplier
                elif window == BurnRateWindow.MEDIUM_6H:
                    threshold = self.slo_config.medium_burn_multiplier
                else:
                    threshold = self.slo_config.slow_burn_multiplier
                
                # Check if burn rate exceeds threshold
                if burn_rate > threshold:
                    # Calculate remaining budget
                    if slo_type == SLOType.ERROR_RATE:
                        total_budget = self.slo_config.error_rate_target * self.slo_config.window_3d_seconds
                        remaining = max(0, total_budget - self._error_budget_consumed[neighborhood])
                        message = (
                            f"Error budget burning at {burn_rate:.1f}x rate. "
                            f"Expected: {threshold:.1f}x. "
                            f"Budget remaining: {self._format_duration(remaining)}"
                        )
                    else:
                        remaining = 0
                        message = f"Latency SLO burning at {burn_rate:.1f}x rate"
                    
                    # Determine severity
                    severity = "critical" if burn_rate > threshold * 2 else "warning"
                    
                    alert = SLOAlert(
                        alert_id=f"{neighborhood}-{slo_type.value}-{window.value}",
                        neighborhood=neighborhood,
                        slo_type=slo_type,
                        burn_rate=burn_rate,
                        threshold=threshold,
                        budget_remaining_seconds=remaining,
                        budget_total_seconds=total_budget if slo_type == SLOType.ERROR_RATE else 0,
                        window=window,
                        severity=severity,
                        message=message,
                        timestamp=now,
                    )
                    
                    alerts.append(alert)
                    self._active_alerts[alert.alert_id] = alert
        
        # Track alert history
        self._alert_history.extend(alerts)
        if len(self._alert_history) > 10000:
            self._alert_history = self._alert_history[-5000:]
        
        return alerts
    
    def get_error_budget_status(self, neighborhood: str) -> Dict:
        """
        Get error budget status for a neighborhood.
        
        Returns:
            Dict with budget consumed, remaining, and projected exhaustion time
        """
        total_budget = self.slo_config.error_rate_target * self.slo_config.window_3d_seconds
        consumed = self._error_budget_consumed.get(neighborhood, 0)
        remaining = max(0, total_budget - consumed)
        
        # Project exhaustion
        now = time.time()
        elapsed = now - self._last_update.get(neighborhood, now)
        
        if elapsed > 0 and consumed > 0:
            burn_rate_per_second = consumed / elapsed
            if burn_rate_per_second > 0:
                exhaustion_seconds = remaining / burn_rate_per_second
            else:
                exhaustion_seconds = float('inf')
        else:
            exhaustion_seconds = float('inf')
        
        return {
            "neighborhood": neighborhood,
            "budget_total_seconds": round(total_budget, 1),
            "budget_consumed_seconds": round(consumed, 1),
            "budget_remaining_seconds": round(remaining, 1),
            "budget_remaining_percentage": round(100 * remaining / total_budget, 2),
            "exhaustion_projected_seconds": (
                round(exhaustion_seconds, 0) if exhaustion_seconds != float('inf') else None
            ),
            "healthy": remaining > (total_budget * 0.5),  # Healthy if >50% remaining
        }
    
    def _format_duration(self, seconds: float) -> str:
        """Format duration in human-readable form."""
        if seconds == float('inf') or seconds is None:
            return "never"
        if seconds < 60:
            return f"{seconds:.0f}s"
        elif seconds < 3600:
            return f"{seconds/60:.1f}m"
        elif seconds < 86400:
            return f"{seconds/3600:.1f}h"
        else:
            return f"{seconds/86400:.1f}d"
    
    def reset_budget(self, neighborhood: str):
        """Reset error budget (e.g., after maintenance)."""
        with self._lock:
            self._error_budget_consumed[neighborhood] = 0.0
            for metrics in self._metrics.get(neighborhood, {}).values():
                metrics.reset()
            
            # Clear related alerts
            alert_ids_to_clear = [
                aid for aid, alert in self._active_alerts.items()
                if alert.neighborhood == neighborhood
            ]
            for aid in alert_ids_to_clear:
                del self._active_alerts[aid]
