# =============================================================================
# Flink JobManager Configuration
# =============================================================================

# JVM options
env.java.opts.jobmanager: -Xms1536m -Xmx1536m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8

# Metrics
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9248
