# =============================================================================
# Flink TaskManager Configuration
# =============================================================================

# JVM options
env.java.opts.taskmanager: -Xms3072m -Xmx3072m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+AlwaysPreTouch

# Metrics
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9249
